// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Task.proto

package pb.xiugou.x1.protobuf.task;

public final class Task {
  private Task() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code pb.PbTaskSystemType}
   */
  public enum PbTaskSystemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *什么都不是
     * </pre>
     *
     * <code>NONE_TASK_TYPE = 0;</code>
     */
    NONE_TASK_TYPE(0),
    /**
     * <pre>
     *主线任务
     * </pre>
     *
     * <code>MAINLINE = 1;</code>
     */
    MAINLINE(1),
    /**
     * <pre>
     *每日任务
     * </pre>
     *
     * <code>DAILY_TASK = 2;</code>
     */
    DAILY_TASK(2),
    /**
     * <pre>
     *每周任务
     * </pre>
     *
     * <code>WEEKLY_TASK = 3;</code>
     */
    WEEKLY_TASK(3),
    /**
     * <pre>
     *七日目标
     * </pre>
     *
     * <code>QRMB_TASK = 4;</code>
     */
    QRMB_TASK(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *什么都不是
     * </pre>
     *
     * <code>NONE_TASK_TYPE = 0;</code>
     */
    public static final int NONE_TASK_TYPE_VALUE = 0;
    /**
     * <pre>
     *主线任务
     * </pre>
     *
     * <code>MAINLINE = 1;</code>
     */
    public static final int MAINLINE_VALUE = 1;
    /**
     * <pre>
     *每日任务
     * </pre>
     *
     * <code>DAILY_TASK = 2;</code>
     */
    public static final int DAILY_TASK_VALUE = 2;
    /**
     * <pre>
     *每周任务
     * </pre>
     *
     * <code>WEEKLY_TASK = 3;</code>
     */
    public static final int WEEKLY_TASK_VALUE = 3;
    /**
     * <pre>
     *七日目标
     * </pre>
     *
     * <code>QRMB_TASK = 4;</code>
     */
    public static final int QRMB_TASK_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PbTaskSystemType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PbTaskSystemType forNumber(int value) {
      switch (value) {
        case 0: return NONE_TASK_TYPE;
        case 1: return MAINLINE;
        case 2: return DAILY_TASK;
        case 3: return WEEKLY_TASK;
        case 4: return QRMB_TASK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PbTaskSystemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PbTaskSystemType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PbTaskSystemType>() {
            public PbTaskSystemType findValueByNumber(int number) {
              return PbTaskSystemType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.task.Task.getDescriptor().getEnumTypes().get(0);
    }

    private static final PbTaskSystemType[] VALUES = values();

    public static PbTaskSystemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PbTaskSystemType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pb.PbTaskSystemType)
  }

  public interface PlayerTaskChangeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.PlayerTaskChangeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *任务系统类型，对应PbTaskSystemType
     * </pre>
     *
     * <code>int32 task_system_type = 1;</code>
     * @return The taskSystemType.
     */
    int getTaskSystemType();

    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask> 
        getTasksList();
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask getTasks(int index);
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    int getTasksCount();
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    java.util.List<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder> 
        getTasksOrBuilderList();
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder getTasksOrBuilder(
        int index);
  }
  /**
   * <pre>
   *玩家任务变化推送
   * </pre>
   *
   * Protobuf type {@code pb.PlayerTaskChangeMessage}
   */
  public  static final class PlayerTaskChangeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.PlayerTaskChangeMessage)
      PlayerTaskChangeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerTaskChangeMessage.newBuilder() to construct.
    private PlayerTaskChangeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerTaskChangeMessage() {
      tasks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerTaskChangeMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerTaskChangeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              taskSystemType_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tasks_ = new java.util.ArrayList<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask>();
                mutable_bitField0_ |= 0x00000001;
              }
              tasks_.add(
                  input.readMessage(pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tasks_ = java.util.Collections.unmodifiableList(tasks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.task.Task.internal_static_pb_PlayerTaskChangeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.task.Task.internal_static_pb_PlayerTaskChangeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.class, pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.PlayerTaskChangeMessage.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 1300001;</code>
       */
      ID(1300001),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 1300001;</code>
       */
      public static final int ID_VALUE = 1300001;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1300001: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.PlayerTaskChangeMessage.Proto)
    }

    public static final int TASK_SYSTEM_TYPE_FIELD_NUMBER = 1;
    private int taskSystemType_;
    /**
     * <pre>
     *任务系统类型，对应PbTaskSystemType
     * </pre>
     *
     * <code>int32 task_system_type = 1;</code>
     * @return The taskSystemType.
     */
    public int getTaskSystemType() {
      return taskSystemType_;
    }

    public static final int TASKS_FIELD_NUMBER = 2;
    private java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask> tasks_;
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    public java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask> getTasksList() {
      return tasks_;
    }
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    public java.util.List<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder> 
        getTasksOrBuilderList() {
      return tasks_;
    }
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    public int getTasksCount() {
      return tasks_.size();
    }
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask getTasks(int index) {
      return tasks_.get(index);
    }
    /**
     * <pre>
     *有数据变化的任务
     * </pre>
     *
     * <code>repeated .pb.PbTask tasks = 2;</code>
     */
    public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder getTasksOrBuilder(
        int index) {
      return tasks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskSystemType_ != 0) {
        output.writeInt32(1, taskSystemType_);
      }
      for (int i = 0; i < tasks_.size(); i++) {
        output.writeMessage(2, tasks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskSystemType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, taskSystemType_);
      }
      for (int i = 0; i < tasks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tasks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage other = (pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage) obj;

      if (getTaskSystemType()
          != other.getTaskSystemType()) return false;
      if (!getTasksList()
          .equals(other.getTasksList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASK_SYSTEM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTaskSystemType();
      if (getTasksCount() > 0) {
        hash = (37 * hash) + TASKS_FIELD_NUMBER;
        hash = (53 * hash) + getTasksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *玩家任务变化推送
     * </pre>
     *
     * Protobuf type {@code pb.PlayerTaskChangeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.PlayerTaskChangeMessage)
        pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.task.Task.internal_static_pb_PlayerTaskChangeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.task.Task.internal_static_pb_PlayerTaskChangeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.class, pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTasksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskSystemType_ = 0;

        if (tasksBuilder_ == null) {
          tasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tasksBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.task.Task.internal_static_pb_PlayerTaskChangeMessage_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage build() {
        pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage buildPartial() {
        pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage result = new pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage(this);
        int from_bitField0_ = bitField0_;
        result.taskSystemType_ = taskSystemType_;
        if (tasksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tasks_ = java.util.Collections.unmodifiableList(tasks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tasks_ = tasks_;
        } else {
          result.tasks_ = tasksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage) {
          return mergeFrom((pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage other) {
        if (other == pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage.getDefaultInstance()) return this;
        if (other.getTaskSystemType() != 0) {
          setTaskSystemType(other.getTaskSystemType());
        }
        if (tasksBuilder_ == null) {
          if (!other.tasks_.isEmpty()) {
            if (tasks_.isEmpty()) {
              tasks_ = other.tasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTasksIsMutable();
              tasks_.addAll(other.tasks_);
            }
            onChanged();
          }
        } else {
          if (!other.tasks_.isEmpty()) {
            if (tasksBuilder_.isEmpty()) {
              tasksBuilder_.dispose();
              tasksBuilder_ = null;
              tasks_ = other.tasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tasksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTasksFieldBuilder() : null;
            } else {
              tasksBuilder_.addAllMessages(other.tasks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int taskSystemType_ ;
      /**
       * <pre>
       *任务系统类型，对应PbTaskSystemType
       * </pre>
       *
       * <code>int32 task_system_type = 1;</code>
       * @return The taskSystemType.
       */
      public int getTaskSystemType() {
        return taskSystemType_;
      }
      /**
       * <pre>
       *任务系统类型，对应PbTaskSystemType
       * </pre>
       *
       * <code>int32 task_system_type = 1;</code>
       * @param value The taskSystemType to set.
       * @return This builder for chaining.
       */
      public Builder setTaskSystemType(int value) {
        
        taskSystemType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *任务系统类型，对应PbTaskSystemType
       * </pre>
       *
       * <code>int32 task_system_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskSystemType() {
        
        taskSystemType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask> tasks_ =
        java.util.Collections.emptyList();
      private void ensureTasksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tasks_ = new java.util.ArrayList<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask>(tasks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder> tasksBuilder_;

      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask> getTasksList() {
        if (tasksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tasks_);
        } else {
          return tasksBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public int getTasksCount() {
        if (tasksBuilder_ == null) {
          return tasks_.size();
        } else {
          return tasksBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask getTasks(int index) {
        if (tasksBuilder_ == null) {
          return tasks_.get(index);
        } else {
          return tasksBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder setTasks(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.set(index, value);
          onChanged();
        } else {
          tasksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder setTasks(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.set(index, builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder addTasks(pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.add(value);
          onChanged();
        } else {
          tasksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder addTasks(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.add(index, value);
          onChanged();
        } else {
          tasksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder addTasks(
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.add(builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder addTasks(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.add(index, builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder addAllTasks(
          java.lang.Iterable<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask> values) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tasks_);
          onChanged();
        } else {
          tasksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder clearTasks() {
        if (tasksBuilder_ == null) {
          tasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tasksBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public Builder removeTasks(int index) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.remove(index);
          onChanged();
        } else {
          tasksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder getTasksBuilder(
          int index) {
        return getTasksFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder getTasksOrBuilder(
          int index) {
        if (tasksBuilder_ == null) {
          return tasks_.get(index);  } else {
          return tasksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public java.util.List<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder> 
           getTasksOrBuilderList() {
        if (tasksBuilder_ != null) {
          return tasksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tasks_);
        }
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder addTasksBuilder() {
        return getTasksFieldBuilder().addBuilder(
            pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.getDefaultInstance());
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder addTasksBuilder(
          int index) {
        return getTasksFieldBuilder().addBuilder(
            index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.getDefaultInstance());
      }
      /**
       * <pre>
       *有数据变化的任务
       * </pre>
       *
       * <code>repeated .pb.PbTask tasks = 2;</code>
       */
      public java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder> 
           getTasksBuilderList() {
        return getTasksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder> 
          getTasksFieldBuilder() {
        if (tasksBuilder_ == null) {
          tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTask.Builder, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbTaskOrBuilder>(
                  tasks_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tasks_ = null;
        }
        return tasksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.PlayerTaskChangeMessage)
    }

    // @@protoc_insertion_point(class_scope:pb.PlayerTaskChangeMessage)
    private static final pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage();
    }

    public static pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerTaskChangeMessage>
        PARSER = new com.google.protobuf.AbstractParser<PlayerTaskChangeMessage>() {
      @java.lang.Override
      public PlayerTaskChangeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerTaskChangeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerTaskChangeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerTaskChangeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.task.Task.PlayerTaskChangeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PlayerTaskChangeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PlayerTaskChangeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTask.proto\022\002pb\032\020MiniStruct.proto\"n\n\027Pl" +
      "ayerTaskChangeMessage\022\030\n\020task_system_typ" +
      "e\030\001 \001(\005\022\031\n\005tasks\030\002 \003(\0132\n.pb.PbTask\"\036\n\005Pr" +
      "oto\022\013\n\007UNKNOWN\020\000\022\010\n\002ID\020\241\254O*d\n\020PbTaskSyst" +
      "emType\022\022\n\016NONE_TASK_TYPE\020\000\022\014\n\010MAINLINE\020\001" +
      "\022\016\n\nDAILY_TASK\020\002\022\017\n\013WEEKLY_TASK\020\003\022\r\n\tQRM" +
      "B_TASK\020\004B4\n\032pb.xiugou.x1.protobuf.task\252\002" +
      "\025pb.xiugou.x1.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.getDescriptor(),
        });
    internal_static_pb_PlayerTaskChangeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_PlayerTaskChangeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PlayerTaskChangeMessage_descriptor,
        new java.lang.String[] { "TaskSystemType", "Tasks", });
    pb.xiugou.x1.protobuf.ministruct.MiniStruct.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
