// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SanQiHuYu.proto

package pb.xiugou.x1.protobuf.sanqihuyu;

public final class SanQiHuYu {
  private SanQiHuYu() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SanQiHuYuInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.SanQiHuYuInfoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否已领取调查问卷奖励
     * </pre>
     *
     * <code>bool ask_list = 1;</code>
     * @return The askList.
     */
    boolean getAskList();
  }
  /**
   * <pre>
   *37互娱的数据
   * </pre>
   *
   * Protobuf type {@code pb.SanQiHuYuInfoResponse}
   */
  public  static final class SanQiHuYuInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.SanQiHuYuInfoResponse)
      SanQiHuYuInfoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SanQiHuYuInfoResponse.newBuilder() to construct.
    private SanQiHuYuInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SanQiHuYuInfoResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SanQiHuYuInfoResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SanQiHuYuInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              askList_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.class, pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.SanQiHuYuInfoResponse.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 3200101;</code>
       */
      ID(3200101),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 3200101;</code>
       */
      public static final int ID_VALUE = 3200101;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 3200101: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.SanQiHuYuInfoResponse.Proto)
    }

    public static final int ASK_LIST_FIELD_NUMBER = 1;
    private boolean askList_;
    /**
     * <pre>
     *是否已领取调查问卷奖励
     * </pre>
     *
     * <code>bool ask_list = 1;</code>
     * @return The askList.
     */
    public boolean getAskList() {
      return askList_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (askList_ != false) {
        output.writeBool(1, askList_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (askList_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, askList_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse other = (pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse) obj;

      if (getAskList()
          != other.getAskList()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ASK_LIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAskList());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *37互娱的数据
     * </pre>
     *
     * Protobuf type {@code pb.SanQiHuYuInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.SanQiHuYuInfoResponse)
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuInfoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.class, pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        askList_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuInfoResponse_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse build() {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse buildPartial() {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse result = new pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse(this);
        result.askList_ = askList_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse) {
          return mergeFrom((pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse other) {
        if (other == pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse.getDefaultInstance()) return this;
        if (other.getAskList() != false) {
          setAskList(other.getAskList());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean askList_ ;
      /**
       * <pre>
       *是否已领取调查问卷奖励
       * </pre>
       *
       * <code>bool ask_list = 1;</code>
       * @return The askList.
       */
      public boolean getAskList() {
        return askList_;
      }
      /**
       * <pre>
       *是否已领取调查问卷奖励
       * </pre>
       *
       * <code>bool ask_list = 1;</code>
       * @param value The askList to set.
       * @return This builder for chaining.
       */
      public Builder setAskList(boolean value) {
        
        askList_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否已领取调查问卷奖励
       * </pre>
       *
       * <code>bool ask_list = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAskList() {
        
        askList_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.SanQiHuYuInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.SanQiHuYuInfoResponse)
    private static final pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse();
    }

    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SanQiHuYuInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<SanQiHuYuInfoResponse>() {
      @java.lang.Override
      public SanQiHuYuInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SanQiHuYuInfoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SanQiHuYuInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SanQiHuYuInfoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SanQiHuYuJumpAskRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.SanQiHuYuJumpAskRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *跳转到调查问卷
   * </pre>
   *
   * Protobuf type {@code pb.SanQiHuYuJumpAskRequest}
   */
  public  static final class SanQiHuYuJumpAskRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.SanQiHuYuJumpAskRequest)
      SanQiHuYuJumpAskRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SanQiHuYuJumpAskRequest.newBuilder() to construct.
    private SanQiHuYuJumpAskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SanQiHuYuJumpAskRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SanQiHuYuJumpAskRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SanQiHuYuJumpAskRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.class, pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.SanQiHuYuJumpAskRequest.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 3200102;</code>
       */
      ID(3200102),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 3200102;</code>
       */
      public static final int ID_VALUE = 3200102;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 3200102: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.SanQiHuYuJumpAskRequest.Proto)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest other = (pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *跳转到调查问卷
     * </pre>
     *
     * Protobuf type {@code pb.SanQiHuYuJumpAskRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.SanQiHuYuJumpAskRequest)
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.class, pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskRequest_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest build() {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest buildPartial() {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest result = new pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest) {
          return mergeFrom((pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest other) {
        if (other == pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.SanQiHuYuJumpAskRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.SanQiHuYuJumpAskRequest)
    private static final pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest();
    }

    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SanQiHuYuJumpAskRequest>
        PARSER = new com.google.protobuf.AbstractParser<SanQiHuYuJumpAskRequest>() {
      @java.lang.Override
      public SanQiHuYuJumpAskRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SanQiHuYuJumpAskRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SanQiHuYuJumpAskRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SanQiHuYuJumpAskRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SanQiHuYuJumpAskResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.SanQiHuYuJumpAskResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否已领取调查问卷奖励
     * </pre>
     *
     * <code>bool ask_list = 1;</code>
     * @return The askList.
     */
    boolean getAskList();
  }
  /**
   * Protobuf type {@code pb.SanQiHuYuJumpAskResponse}
   */
  public  static final class SanQiHuYuJumpAskResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.SanQiHuYuJumpAskResponse)
      SanQiHuYuJumpAskResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SanQiHuYuJumpAskResponse.newBuilder() to construct.
    private SanQiHuYuJumpAskResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SanQiHuYuJumpAskResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SanQiHuYuJumpAskResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SanQiHuYuJumpAskResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              askList_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.class, pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.SanQiHuYuJumpAskResponse.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 3200102;</code>
       */
      ID(3200102),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 3200102;</code>
       */
      public static final int ID_VALUE = 3200102;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 3200102: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.SanQiHuYuJumpAskResponse.Proto)
    }

    public static final int ASK_LIST_FIELD_NUMBER = 1;
    private boolean askList_;
    /**
     * <pre>
     *是否已领取调查问卷奖励
     * </pre>
     *
     * <code>bool ask_list = 1;</code>
     * @return The askList.
     */
    public boolean getAskList() {
      return askList_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (askList_ != false) {
        output.writeBool(1, askList_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (askList_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, askList_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse other = (pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse) obj;

      if (getAskList()
          != other.getAskList()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ASK_LIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAskList());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.SanQiHuYuJumpAskResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.SanQiHuYuJumpAskResponse)
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.class, pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        askList_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.internal_static_pb_SanQiHuYuJumpAskResponse_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse build() {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse buildPartial() {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse result = new pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse(this);
        result.askList_ = askList_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse) {
          return mergeFrom((pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse other) {
        if (other == pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse.getDefaultInstance()) return this;
        if (other.getAskList() != false) {
          setAskList(other.getAskList());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean askList_ ;
      /**
       * <pre>
       *是否已领取调查问卷奖励
       * </pre>
       *
       * <code>bool ask_list = 1;</code>
       * @return The askList.
       */
      public boolean getAskList() {
        return askList_;
      }
      /**
       * <pre>
       *是否已领取调查问卷奖励
       * </pre>
       *
       * <code>bool ask_list = 1;</code>
       * @param value The askList to set.
       * @return This builder for chaining.
       */
      public Builder setAskList(boolean value) {
        
        askList_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否已领取调查问卷奖励
       * </pre>
       *
       * <code>bool ask_list = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAskList() {
        
        askList_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.SanQiHuYuJumpAskResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.SanQiHuYuJumpAskResponse)
    private static final pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse();
    }

    public static pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SanQiHuYuJumpAskResponse>
        PARSER = new com.google.protobuf.AbstractParser<SanQiHuYuJumpAskResponse>() {
      @java.lang.Override
      public SanQiHuYuJumpAskResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SanQiHuYuJumpAskResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SanQiHuYuJumpAskResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SanQiHuYuJumpAskResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.sanqihuyu.SanQiHuYu.SanQiHuYuJumpAskResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SanQiHuYuInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SanQiHuYuInfoResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SanQiHuYuJumpAskRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SanQiHuYuJumpAskRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SanQiHuYuJumpAskResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SanQiHuYuJumpAskResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SanQiHuYu.proto\022\002pb\"J\n\025SanQiHuYuInfoRe" +
      "sponse\022\020\n\010ask_list\030\001 \001(\010\"\037\n\005Proto\022\013\n\007UNK" +
      "NOWN\020\000\022\t\n\002ID\020\345\250\303\001\":\n\027SanQiHuYuJumpAskReq" +
      "uest\"\037\n\005Proto\022\013\n\007UNKNOWN\020\000\022\t\n\002ID\020\346\250\303\001\"M\n" +
      "\030SanQiHuYuJumpAskResponse\022\020\n\010ask_list\030\001 " +
      "\001(\010\"\037\n\005Proto\022\013\n\007UNKNOWN\020\000\022\t\n\002ID\020\346\250\303\001B9\n\037" +
      "pb.xiugou.x1.protobuf.sanqihuyu\252\002\025pb.xiu" +
      "gou.x1.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_SanQiHuYuInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_SanQiHuYuInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SanQiHuYuInfoResponse_descriptor,
        new java.lang.String[] { "AskList", });
    internal_static_pb_SanQiHuYuJumpAskRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_SanQiHuYuJumpAskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SanQiHuYuJumpAskRequest_descriptor,
        new java.lang.String[] { });
    internal_static_pb_SanQiHuYuJumpAskResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_SanQiHuYuJumpAskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SanQiHuYuJumpAskResponse_descriptor,
        new java.lang.String[] { "AskList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
