// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: P1008ChongBang.proto

package pb.xiugou.x1.protobuf.promotion;

public final class P1008ChongBang {
  private P1008ChongBang() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChongBangRewardPreviewRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ChongBangRewardPreviewRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *活动类型ID
     * </pre>
     *
     * <code>int32 type_id = 1;</code>
     * @return The typeId.
     */
    int getTypeId();
  }
  /**
   * <pre>
   *冲榜奖励预览
   * </pre>
   *
   * Protobuf type {@code pb.ChongBangRewardPreviewRequest}
   */
  public  static final class ChongBangRewardPreviewRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ChongBangRewardPreviewRequest)
      ChongBangRewardPreviewRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChongBangRewardPreviewRequest.newBuilder() to construct.
    private ChongBangRewardPreviewRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChongBangRewardPreviewRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChongBangRewardPreviewRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChongBangRewardPreviewRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              typeId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.class, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.ChongBangRewardPreviewRequest.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 2100801;</code>
       */
      ID(2100801),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 2100801;</code>
       */
      public static final int ID_VALUE = 2100801;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 2100801: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.ChongBangRewardPreviewRequest.Proto)
    }

    public static final int TYPE_ID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <pre>
     *活动类型ID
     * </pre>
     *
     * <code>int32 type_id = 1;</code>
     * @return The typeId.
     */
    public int getTypeId() {
      return typeId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeId_ != 0) {
        output.writeInt32(1, typeId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, typeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest other = (pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest) obj;

      if (getTypeId()
          != other.getTypeId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *冲榜奖励预览
     * </pre>
     *
     * Protobuf type {@code pb.ChongBangRewardPreviewRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ChongBangRewardPreviewRequest)
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.class, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewRequest_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest build() {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest buildPartial() {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest result = new pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest(this);
        result.typeId_ = typeId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest) {
          return mergeFrom((pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest other) {
        if (other == pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest.getDefaultInstance()) return this;
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int typeId_ ;
      /**
       * <pre>
       *活动类型ID
       * </pre>
       *
       * <code>int32 type_id = 1;</code>
       * @return The typeId.
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <pre>
       *活动类型ID
       * </pre>
       *
       * <code>int32 type_id = 1;</code>
       * @param value The typeId to set.
       * @return This builder for chaining.
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *活动类型ID
       * </pre>
       *
       * <code>int32 type_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ChongBangRewardPreviewRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.ChongBangRewardPreviewRequest)
    private static final pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest();
    }

    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChongBangRewardPreviewRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChongBangRewardPreviewRequest>() {
      @java.lang.Override
      public ChongBangRewardPreviewRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChongBangRewardPreviewRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChongBangRewardPreviewRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChongBangRewardPreviewRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChongBangRewardPreviewResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ChongBangRewardPreviewResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *活动类型ID
     * </pre>
     *
     * <code>int32 type_id = 1;</code>
     * @return The typeId.
     */
    int getTypeId();

    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    java.util.List<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward> 
        getRewardsList();
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward getRewards(int index);
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    int getRewardsCount();
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    java.util.List<? extends pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder> 
        getRewardsOrBuilderList();
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder getRewardsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pb.ChongBangRewardPreviewResponse}
   */
  public  static final class ChongBangRewardPreviewResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ChongBangRewardPreviewResponse)
      ChongBangRewardPreviewResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChongBangRewardPreviewResponse.newBuilder() to construct.
    private ChongBangRewardPreviewResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChongBangRewardPreviewResponse() {
      rewards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChongBangRewardPreviewResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChongBangRewardPreviewResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              typeId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                rewards_ = new java.util.ArrayList<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward>();
                mutable_bitField0_ |= 0x00000001;
              }
              rewards_.add(
                  input.readMessage(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          rewards_ = java.util.Collections.unmodifiableList(rewards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.class, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.ChongBangRewardPreviewResponse.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 2100801;</code>
       */
      ID(2100801),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 2100801;</code>
       */
      public static final int ID_VALUE = 2100801;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 2100801: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.ChongBangRewardPreviewResponse.Proto)
    }

    public static final int TYPE_ID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <pre>
     *活动类型ID
     * </pre>
     *
     * <code>int32 type_id = 1;</code>
     * @return The typeId.
     */
    public int getTypeId() {
      return typeId_;
    }

    public static final int REWARDS_FIELD_NUMBER = 2;
    private java.util.List<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward> rewards_;
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    public java.util.List<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward> getRewardsList() {
      return rewards_;
    }
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    public java.util.List<? extends pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder> 
        getRewardsOrBuilderList() {
      return rewards_;
    }
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    public int getRewardsCount() {
      return rewards_.size();
    }
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward getRewards(int index) {
      return rewards_.get(index);
    }
    /**
     * <pre>
     *奖励预览列表
     * </pre>
     *
     * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
     */
    public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder getRewardsOrBuilder(
        int index) {
      return rewards_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeId_ != 0) {
        output.writeInt32(1, typeId_);
      }
      for (int i = 0; i < rewards_.size(); i++) {
        output.writeMessage(2, rewards_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, typeId_);
      }
      for (int i = 0; i < rewards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rewards_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse other = (pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse) obj;

      if (getTypeId()
          != other.getTypeId()) return false;
      if (!getRewardsList()
          .equals(other.getRewardsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      if (getRewardsCount() > 0) {
        hash = (37 * hash) + REWARDS_FIELD_NUMBER;
        hash = (53 * hash) + getRewardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ChongBangRewardPreviewResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ChongBangRewardPreviewResponse)
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.class, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRewardsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeId_ = 0;

        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rewardsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_ChongBangRewardPreviewResponse_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse build() {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse buildPartial() {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse result = new pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse(this);
        int from_bitField0_ = bitField0_;
        result.typeId_ = typeId_;
        if (rewardsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            rewards_ = java.util.Collections.unmodifiableList(rewards_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rewards_ = rewards_;
        } else {
          result.rewards_ = rewardsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse) {
          return mergeFrom((pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse other) {
        if (other == pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse.getDefaultInstance()) return this;
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (rewardsBuilder_ == null) {
          if (!other.rewards_.isEmpty()) {
            if (rewards_.isEmpty()) {
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRewardsIsMutable();
              rewards_.addAll(other.rewards_);
            }
            onChanged();
          }
        } else {
          if (!other.rewards_.isEmpty()) {
            if (rewardsBuilder_.isEmpty()) {
              rewardsBuilder_.dispose();
              rewardsBuilder_ = null;
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rewardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardsFieldBuilder() : null;
            } else {
              rewardsBuilder_.addAllMessages(other.rewards_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int typeId_ ;
      /**
       * <pre>
       *活动类型ID
       * </pre>
       *
       * <code>int32 type_id = 1;</code>
       * @return The typeId.
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <pre>
       *活动类型ID
       * </pre>
       *
       * <code>int32 type_id = 1;</code>
       * @param value The typeId to set.
       * @return This builder for chaining.
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *活动类型ID
       * </pre>
       *
       * <code>int32 type_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward> rewards_ =
        java.util.Collections.emptyList();
      private void ensureRewardsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rewards_ = new java.util.ArrayList<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward>(rewards_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder> rewardsBuilder_;

      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public java.util.List<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward> getRewardsList() {
        if (rewardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rewards_);
        } else {
          return rewardsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public int getRewardsCount() {
        if (rewardsBuilder_ == null) {
          return rewards_.size();
        } else {
          return rewardsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward getRewards(int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);
        } else {
          return rewardsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder setRewards(
          int index, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.set(index, value);
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder setRewards(
          int index, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder addRewards(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder addRewards(
          int index, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(index, value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder addRewards(
          pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder addRewards(
          int index, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder addAllRewards(
          java.lang.Iterable<? extends pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward> values) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rewards_);
          onChanged();
        } else {
          rewardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder clearRewards() {
        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rewardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public Builder removeRewards(int index) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.remove(index);
          onChanged();
        } else {
          rewardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder getRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder getRewardsOrBuilder(
          int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);  } else {
          return rewardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public java.util.List<? extends pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder> 
           getRewardsOrBuilderList() {
        if (rewardsBuilder_ != null) {
          return rewardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rewards_);
        }
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder addRewardsBuilder() {
        return getRewardsFieldBuilder().addBuilder(
            pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.getDefaultInstance());
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder addRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().addBuilder(
            index, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.getDefaultInstance());
      }
      /**
       * <pre>
       *奖励预览列表
       * </pre>
       *
       * <code>repeated .pb.PbChongBangReward rewards = 2;</code>
       */
      public java.util.List<pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder> 
           getRewardsBuilderList() {
        return getRewardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder> 
          getRewardsFieldBuilder() {
        if (rewardsBuilder_ == null) {
          rewardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder>(
                  rewards_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          rewards_ = null;
        }
        return rewardsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ChongBangRewardPreviewResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.ChongBangRewardPreviewResponse)
    private static final pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse();
    }

    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChongBangRewardPreviewResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChongBangRewardPreviewResponse>() {
      @java.lang.Override
      public ChongBangRewardPreviewResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChongBangRewardPreviewResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChongBangRewardPreviewResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChongBangRewardPreviewResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.ChongBangRewardPreviewResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbChongBangRewardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.PbChongBangReward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 rank_up = 1;</code>
     * @return The rankUp.
     */
    int getRankUp();

    /**
     * <code>int32 rank_down = 2;</code>
     * @return The rankDown.
     */
    int getRankDown();

    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem> 
        getItemsList();
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem getItems(int index);
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    java.util.List<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pb.PbChongBangReward}
   */
  public  static final class PbChongBangReward extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.PbChongBangReward)
      PbChongBangRewardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbChongBangReward.newBuilder() to construct.
    private PbChongBangReward(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbChongBangReward() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PbChongBangReward();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbChongBangReward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rankUp_ = input.readInt32();
              break;
            }
            case 16: {

              rankDown_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_PbChongBangReward_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_PbChongBangReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.class, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder.class);
    }

    public static final int RANK_UP_FIELD_NUMBER = 1;
    private int rankUp_;
    /**
     * <code>int32 rank_up = 1;</code>
     * @return The rankUp.
     */
    public int getRankUp() {
      return rankUp_;
    }

    public static final int RANK_DOWN_FIELD_NUMBER = 2;
    private int rankDown_;
    /**
     * <code>int32 rank_down = 2;</code>
     * @return The rankDown.
     */
    public int getRankDown() {
      return rankDown_;
    }

    public static final int ITEMS_FIELD_NUMBER = 3;
    private java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem> items_;
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    public java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    public java.util.List<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .pb.PbItem items = 3;</code>
     */
    public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rankUp_ != 0) {
        output.writeInt32(1, rankUp_);
      }
      if (rankDown_ != 0) {
        output.writeInt32(2, rankDown_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(3, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rankUp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rankUp_);
      }
      if (rankDown_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rankDown_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward other = (pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward) obj;

      if (getRankUp()
          != other.getRankUp()) return false;
      if (getRankDown()
          != other.getRankDown()) return false;
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RANK_UP_FIELD_NUMBER;
      hash = (53 * hash) + getRankUp();
      hash = (37 * hash) + RANK_DOWN_FIELD_NUMBER;
      hash = (53 * hash) + getRankDown();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.PbChongBangReward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.PbChongBangReward)
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_PbChongBangReward_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_PbChongBangReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.class, pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rankUp_ = 0;

        rankDown_ = 0;

        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.internal_static_pb_PbChongBangReward_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward build() {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward buildPartial() {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward result = new pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward(this);
        int from_bitField0_ = bitField0_;
        result.rankUp_ = rankUp_;
        result.rankDown_ = rankDown_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward) {
          return mergeFrom((pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward other) {
        if (other == pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward.getDefaultInstance()) return this;
        if (other.getRankUp() != 0) {
          setRankUp(other.getRankUp());
        }
        if (other.getRankDown() != 0) {
          setRankDown(other.getRankDown());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rankUp_ ;
      /**
       * <code>int32 rank_up = 1;</code>
       * @return The rankUp.
       */
      public int getRankUp() {
        return rankUp_;
      }
      /**
       * <code>int32 rank_up = 1;</code>
       * @param value The rankUp to set.
       * @return This builder for chaining.
       */
      public Builder setRankUp(int value) {
        
        rankUp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rank_up = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankUp() {
        
        rankUp_ = 0;
        onChanged();
        return this;
      }

      private int rankDown_ ;
      /**
       * <code>int32 rank_down = 2;</code>
       * @return The rankDown.
       */
      public int getRankDown() {
        return rankDown_;
      }
      /**
       * <code>int32 rank_down = 2;</code>
       * @param value The rankDown to set.
       * @return This builder for chaining.
       */
      public Builder setRankDown(int value) {
        
        rankDown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rank_down = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankDown() {
        
        rankDown_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder setItems(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder setItems(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder addItems(pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder addItems(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder addItems(
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder addItems(
          int index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public java.util.List<? extends pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.PbItem items = 3;</code>
       */
      public java.util.List<pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItem.Builder, pb.xiugou.x1.protobuf.ministruct.MiniStruct.PbItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.PbChongBangReward)
    }

    // @@protoc_insertion_point(class_scope:pb.PbChongBangReward)
    private static final pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward();
    }

    public static pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbChongBangReward>
        PARSER = new com.google.protobuf.AbstractParser<PbChongBangReward>() {
      @java.lang.Override
      public PbChongBangReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbChongBangReward(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbChongBangReward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbChongBangReward> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.promotion.P1008ChongBang.PbChongBangReward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ChongBangRewardPreviewRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ChongBangRewardPreviewRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ChongBangRewardPreviewResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ChongBangRewardPreviewResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PbChongBangReward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PbChongBangReward_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024P1008ChongBang.proto\022\002pb\032\020MiniStruct.p" +
      "roto\"Q\n\035ChongBangRewardPreviewRequest\022\017\n" +
      "\007type_id\030\001 \001(\005\"\037\n\005Proto\022\013\n\007UNKNOWN\020\000\022\t\n\002" +
      "ID\020\301\234\200\001\"z\n\036ChongBangRewardPreviewRespons" +
      "e\022\017\n\007type_id\030\001 \001(\005\022&\n\007rewards\030\002 \003(\0132\025.pb" +
      ".PbChongBangReward\"\037\n\005Proto\022\013\n\007UNKNOWN\020\000" +
      "\022\t\n\002ID\020\301\234\200\001\"R\n\021PbChongBangReward\022\017\n\007rank" +
      "_up\030\001 \001(\005\022\021\n\trank_down\030\002 \001(\005\022\031\n\005items\030\003 " +
      "\003(\0132\n.pb.PbItemB9\n\037pb.xiugou.x1.protobuf" +
      ".promotion\252\002\025pb.xiugou.x1.protobufb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.xiugou.x1.protobuf.ministruct.MiniStruct.getDescriptor(),
        });
    internal_static_pb_ChongBangRewardPreviewRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_ChongBangRewardPreviewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ChongBangRewardPreviewRequest_descriptor,
        new java.lang.String[] { "TypeId", });
    internal_static_pb_ChongBangRewardPreviewResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_ChongBangRewardPreviewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ChongBangRewardPreviewResponse_descriptor,
        new java.lang.String[] { "TypeId", "Rewards", });
    internal_static_pb_PbChongBangReward_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_PbChongBangReward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PbChongBangReward_descriptor,
        new java.lang.String[] { "RankUp", "RankDown", "Items", });
    pb.xiugou.x1.protobuf.ministruct.MiniStruct.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
