// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRpc.proto

package pb.xiugou.x1.protobuf.chat;

public final class ChatRpc {
  private ChatRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatToRpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ChatToRpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *频道
     * </pre>
     *
     * <code>int32 channel = 1;</code>
     * @return The channel.
     */
    int getChannel();

    /**
     * <pre>
     *目标ID，好友聊天时传玩家ID
     * </pre>
     *
     * <code>int64 target_id = 2;</code>
     * @return The targetId.
     */
    long getTargetId();

    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return Whether the chatData field is set.
     */
    boolean hasChatData();
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return The chatData.
     */
    pb.xiugou.x1.protobuf.chat.Chat.PbChatData getChatData();
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     */
    pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder getChatDataOrBuilder();

    /**
     * <pre>
     *是否可疑
     * </pre>
     *
     * <code>bool doubt = 4;</code>
     * @return The doubt.
     */
    boolean getDoubt();

    /**
     * <pre>
     *原始内容
     * </pre>
     *
     * <code>string ori_content = 5;</code>
     * @return The oriContent.
     */
    java.lang.String getOriContent();
    /**
     * <pre>
     *原始内容
     * </pre>
     *
     * <code>string ori_content = 5;</code>
     * @return The bytes for oriContent.
     */
    com.google.protobuf.ByteString
        getOriContentBytes();
  }
  /**
   * <pre>
   *聊天远程调用，客户端忽略
   * </pre>
   *
   * Protobuf type {@code pb.ChatToRpcRequest}
   */
  public  static final class ChatToRpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ChatToRpcRequest)
      ChatToRpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatToRpcRequest.newBuilder() to construct.
    private ChatToRpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatToRpcRequest() {
      oriContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatToRpcRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatToRpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              channel_ = input.readInt32();
              break;
            }
            case 16: {

              targetId_ = input.readInt64();
              break;
            }
            case 26: {
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder subBuilder = null;
              if (chatData_ != null) {
                subBuilder = chatData_.toBuilder();
              }
              chatData_ = input.readMessage(pb.xiugou.x1.protobuf.chat.Chat.PbChatData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatData_);
                chatData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              doubt_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              oriContent_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.class, pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.ChatToRpcRequest.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 3610001;</code>
       */
      ID(3610001),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 3610001;</code>
       */
      public static final int ID_VALUE = 3610001;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 3610001: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.ChatToRpcRequest.Proto)
    }

    public static final int CHANNEL_FIELD_NUMBER = 1;
    private int channel_;
    /**
     * <pre>
     *频道
     * </pre>
     *
     * <code>int32 channel = 1;</code>
     * @return The channel.
     */
    public int getChannel() {
      return channel_;
    }

    public static final int TARGET_ID_FIELD_NUMBER = 2;
    private long targetId_;
    /**
     * <pre>
     *目标ID，好友聊天时传玩家ID
     * </pre>
     *
     * <code>int64 target_id = 2;</code>
     * @return The targetId.
     */
    public long getTargetId() {
      return targetId_;
    }

    public static final int CHAT_DATA_FIELD_NUMBER = 3;
    private pb.xiugou.x1.protobuf.chat.Chat.PbChatData chatData_;
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return Whether the chatData field is set.
     */
    public boolean hasChatData() {
      return chatData_ != null;
    }
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return The chatData.
     */
    public pb.xiugou.x1.protobuf.chat.Chat.PbChatData getChatData() {
      return chatData_ == null ? pb.xiugou.x1.protobuf.chat.Chat.PbChatData.getDefaultInstance() : chatData_;
    }
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     */
    public pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder getChatDataOrBuilder() {
      return getChatData();
    }

    public static final int DOUBT_FIELD_NUMBER = 4;
    private boolean doubt_;
    /**
     * <pre>
     *是否可疑
     * </pre>
     *
     * <code>bool doubt = 4;</code>
     * @return The doubt.
     */
    public boolean getDoubt() {
      return doubt_;
    }

    public static final int ORI_CONTENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object oriContent_;
    /**
     * <pre>
     *原始内容
     * </pre>
     *
     * <code>string ori_content = 5;</code>
     * @return The oriContent.
     */
    public java.lang.String getOriContent() {
      java.lang.Object ref = oriContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oriContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *原始内容
     * </pre>
     *
     * <code>string ori_content = 5;</code>
     * @return The bytes for oriContent.
     */
    public com.google.protobuf.ByteString
        getOriContentBytes() {
      java.lang.Object ref = oriContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oriContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (channel_ != 0) {
        output.writeInt32(1, channel_);
      }
      if (targetId_ != 0L) {
        output.writeInt64(2, targetId_);
      }
      if (chatData_ != null) {
        output.writeMessage(3, getChatData());
      }
      if (doubt_ != false) {
        output.writeBool(4, doubt_);
      }
      if (!getOriContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, oriContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channel_);
      }
      if (targetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, targetId_);
      }
      if (chatData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getChatData());
      }
      if (doubt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, doubt_);
      }
      if (!getOriContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, oriContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest other = (pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest) obj;

      if (getChannel()
          != other.getChannel()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (hasChatData() != other.hasChatData()) return false;
      if (hasChatData()) {
        if (!getChatData()
            .equals(other.getChatData())) return false;
      }
      if (getDoubt()
          != other.getDoubt()) return false;
      if (!getOriContent()
          .equals(other.getOriContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetId());
      if (hasChatData()) {
        hash = (37 * hash) + CHAT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getChatData().hashCode();
      }
      hash = (37 * hash) + DOUBT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDoubt());
      hash = (37 * hash) + ORI_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getOriContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *聊天远程调用，客户端忽略
     * </pre>
     *
     * Protobuf type {@code pb.ChatToRpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ChatToRpcRequest)
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.class, pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channel_ = 0;

        targetId_ = 0L;

        if (chatDataBuilder_ == null) {
          chatData_ = null;
        } else {
          chatData_ = null;
          chatDataBuilder_ = null;
        }
        doubt_ = false;

        oriContent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcRequest_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest build() {
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest buildPartial() {
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest result = new pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest(this);
        result.channel_ = channel_;
        result.targetId_ = targetId_;
        if (chatDataBuilder_ == null) {
          result.chatData_ = chatData_;
        } else {
          result.chatData_ = chatDataBuilder_.build();
        }
        result.doubt_ = doubt_;
        result.oriContent_ = oriContent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest) {
          return mergeFrom((pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest other) {
        if (other == pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest.getDefaultInstance()) return this;
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (other.getTargetId() != 0L) {
          setTargetId(other.getTargetId());
        }
        if (other.hasChatData()) {
          mergeChatData(other.getChatData());
        }
        if (other.getDoubt() != false) {
          setDoubt(other.getDoubt());
        }
        if (!other.getOriContent().isEmpty()) {
          oriContent_ = other.oriContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int channel_ ;
      /**
       * <pre>
       *频道
       * </pre>
       *
       * <code>int32 channel = 1;</code>
       * @return The channel.
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <pre>
       *频道
       * </pre>
       *
       * <code>int32 channel = 1;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(int value) {
        
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *频道
       * </pre>
       *
       * <code>int32 channel = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = 0;
        onChanged();
        return this;
      }

      private long targetId_ ;
      /**
       * <pre>
       *目标ID，好友聊天时传玩家ID
       * </pre>
       *
       * <code>int64 target_id = 2;</code>
       * @return The targetId.
       */
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <pre>
       *目标ID，好友聊天时传玩家ID
       * </pre>
       *
       * <code>int64 target_id = 2;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(long value) {
        
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标ID，好友聊天时传玩家ID
       * </pre>
       *
       * <code>int64 target_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        
        targetId_ = 0L;
        onChanged();
        return this;
      }

      private pb.xiugou.x1.protobuf.chat.Chat.PbChatData chatData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.xiugou.x1.protobuf.chat.Chat.PbChatData, pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder, pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder> chatDataBuilder_;
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       * @return Whether the chatData field is set.
       */
      public boolean hasChatData() {
        return chatDataBuilder_ != null || chatData_ != null;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       * @return The chatData.
       */
      public pb.xiugou.x1.protobuf.chat.Chat.PbChatData getChatData() {
        if (chatDataBuilder_ == null) {
          return chatData_ == null ? pb.xiugou.x1.protobuf.chat.Chat.PbChatData.getDefaultInstance() : chatData_;
        } else {
          return chatDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder setChatData(pb.xiugou.x1.protobuf.chat.Chat.PbChatData value) {
        if (chatDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatData_ = value;
          onChanged();
        } else {
          chatDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder setChatData(
          pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder builderForValue) {
        if (chatDataBuilder_ == null) {
          chatData_ = builderForValue.build();
          onChanged();
        } else {
          chatDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder mergeChatData(pb.xiugou.x1.protobuf.chat.Chat.PbChatData value) {
        if (chatDataBuilder_ == null) {
          if (chatData_ != null) {
            chatData_ =
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData.newBuilder(chatData_).mergeFrom(value).buildPartial();
          } else {
            chatData_ = value;
          }
          onChanged();
        } else {
          chatDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder clearChatData() {
        if (chatDataBuilder_ == null) {
          chatData_ = null;
          onChanged();
        } else {
          chatData_ = null;
          chatDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder getChatDataBuilder() {
        
        onChanged();
        return getChatDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder getChatDataOrBuilder() {
        if (chatDataBuilder_ != null) {
          return chatDataBuilder_.getMessageOrBuilder();
        } else {
          return chatData_ == null ?
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData.getDefaultInstance() : chatData_;
        }
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.xiugou.x1.protobuf.chat.Chat.PbChatData, pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder, pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder> 
          getChatDataFieldBuilder() {
        if (chatDataBuilder_ == null) {
          chatDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData, pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder, pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder>(
                  getChatData(),
                  getParentForChildren(),
                  isClean());
          chatData_ = null;
        }
        return chatDataBuilder_;
      }

      private boolean doubt_ ;
      /**
       * <pre>
       *是否可疑
       * </pre>
       *
       * <code>bool doubt = 4;</code>
       * @return The doubt.
       */
      public boolean getDoubt() {
        return doubt_;
      }
      /**
       * <pre>
       *是否可疑
       * </pre>
       *
       * <code>bool doubt = 4;</code>
       * @param value The doubt to set.
       * @return This builder for chaining.
       */
      public Builder setDoubt(boolean value) {
        
        doubt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否可疑
       * </pre>
       *
       * <code>bool doubt = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubt() {
        
        doubt_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object oriContent_ = "";
      /**
       * <pre>
       *原始内容
       * </pre>
       *
       * <code>string ori_content = 5;</code>
       * @return The oriContent.
       */
      public java.lang.String getOriContent() {
        java.lang.Object ref = oriContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oriContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *原始内容
       * </pre>
       *
       * <code>string ori_content = 5;</code>
       * @return The bytes for oriContent.
       */
      public com.google.protobuf.ByteString
          getOriContentBytes() {
        java.lang.Object ref = oriContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oriContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *原始内容
       * </pre>
       *
       * <code>string ori_content = 5;</code>
       * @param value The oriContent to set.
       * @return This builder for chaining.
       */
      public Builder setOriContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oriContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *原始内容
       * </pre>
       *
       * <code>string ori_content = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriContent() {
        
        oriContent_ = getDefaultInstance().getOriContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *原始内容
       * </pre>
       *
       * <code>string ori_content = 5;</code>
       * @param value The bytes for oriContent to set.
       * @return This builder for chaining.
       */
      public Builder setOriContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oriContent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ChatToRpcRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.ChatToRpcRequest)
    private static final pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest();
    }

    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatToRpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChatToRpcRequest>() {
      @java.lang.Override
      public ChatToRpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatToRpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatToRpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatToRpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatToRpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ChatToRpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *频道
     * </pre>
     *
     * <code>int32 channel = 1;</code>
     * @return The channel.
     */
    int getChannel();

    /**
     * <pre>
     *目标ID，好友聊天时传玩家ID
     * </pre>
     *
     * <code>int64 target_id = 2;</code>
     * @return The targetId.
     */
    long getTargetId();

    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return Whether the chatData field is set.
     */
    boolean hasChatData();
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return The chatData.
     */
    pb.xiugou.x1.protobuf.chat.Chat.PbChatData getChatData();
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     */
    pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder getChatDataOrBuilder();

    /**
     * <pre>
     *是否可疑
     * </pre>
     *
     * <code>bool doubt = 4;</code>
     * @return The doubt.
     */
    boolean getDoubt();
  }
  /**
   * Protobuf type {@code pb.ChatToRpcResponse}
   */
  public  static final class ChatToRpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ChatToRpcResponse)
      ChatToRpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatToRpcResponse.newBuilder() to construct.
    private ChatToRpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatToRpcResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatToRpcResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatToRpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              channel_ = input.readInt32();
              break;
            }
            case 16: {

              targetId_ = input.readInt64();
              break;
            }
            case 26: {
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder subBuilder = null;
              if (chatData_ != null) {
                subBuilder = chatData_.toBuilder();
              }
              chatData_ = input.readMessage(pb.xiugou.x1.protobuf.chat.Chat.PbChatData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatData_);
                chatData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              doubt_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.class, pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.ChatToRpcResponse.Proto}
     */
    public enum Proto
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ID = 3610001;</code>
       */
      ID(3610001),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ID = 3610001;</code>
       */
      public static final int ID_VALUE = 3610001;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Proto valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Proto forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 3610001: return ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Proto>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Proto> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Proto>() {
              public Proto findValueByNumber(int number) {
                return Proto.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Proto[] VALUES = values();

      public static Proto valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Proto(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.ChatToRpcResponse.Proto)
    }

    public static final int CHANNEL_FIELD_NUMBER = 1;
    private int channel_;
    /**
     * <pre>
     *频道
     * </pre>
     *
     * <code>int32 channel = 1;</code>
     * @return The channel.
     */
    public int getChannel() {
      return channel_;
    }

    public static final int TARGET_ID_FIELD_NUMBER = 2;
    private long targetId_;
    /**
     * <pre>
     *目标ID，好友聊天时传玩家ID
     * </pre>
     *
     * <code>int64 target_id = 2;</code>
     * @return The targetId.
     */
    public long getTargetId() {
      return targetId_;
    }

    public static final int CHAT_DATA_FIELD_NUMBER = 3;
    private pb.xiugou.x1.protobuf.chat.Chat.PbChatData chatData_;
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return Whether the chatData field is set.
     */
    public boolean hasChatData() {
      return chatData_ != null;
    }
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     * @return The chatData.
     */
    public pb.xiugou.x1.protobuf.chat.Chat.PbChatData getChatData() {
      return chatData_ == null ? pb.xiugou.x1.protobuf.chat.Chat.PbChatData.getDefaultInstance() : chatData_;
    }
    /**
     * <pre>
     *聊天信息
     * </pre>
     *
     * <code>.pb.PbChatData chat_data = 3;</code>
     */
    public pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder getChatDataOrBuilder() {
      return getChatData();
    }

    public static final int DOUBT_FIELD_NUMBER = 4;
    private boolean doubt_;
    /**
     * <pre>
     *是否可疑
     * </pre>
     *
     * <code>bool doubt = 4;</code>
     * @return The doubt.
     */
    public boolean getDoubt() {
      return doubt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (channel_ != 0) {
        output.writeInt32(1, channel_);
      }
      if (targetId_ != 0L) {
        output.writeInt64(2, targetId_);
      }
      if (chatData_ != null) {
        output.writeMessage(3, getChatData());
      }
      if (doubt_ != false) {
        output.writeBool(4, doubt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channel_);
      }
      if (targetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, targetId_);
      }
      if (chatData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getChatData());
      }
      if (doubt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, doubt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse)) {
        return super.equals(obj);
      }
      pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse other = (pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse) obj;

      if (getChannel()
          != other.getChannel()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (hasChatData() != other.hasChatData()) return false;
      if (hasChatData()) {
        if (!getChatData()
            .equals(other.getChatData())) return false;
      }
      if (getDoubt()
          != other.getDoubt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetId());
      if (hasChatData()) {
        hash = (37 * hash) + CHAT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getChatData().hashCode();
      }
      hash = (37 * hash) + DOUBT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDoubt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ChatToRpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ChatToRpcResponse)
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.class, pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.Builder.class);
      }

      // Construct using pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channel_ = 0;

        targetId_ = 0L;

        if (chatDataBuilder_ == null) {
          chatData_ = null;
        } else {
          chatData_ = null;
          chatDataBuilder_ = null;
        }
        doubt_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.internal_static_pb_ChatToRpcResponse_descriptor;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse getDefaultInstanceForType() {
        return pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse build() {
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse buildPartial() {
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse result = new pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse(this);
        result.channel_ = channel_;
        result.targetId_ = targetId_;
        if (chatDataBuilder_ == null) {
          result.chatData_ = chatData_;
        } else {
          result.chatData_ = chatDataBuilder_.build();
        }
        result.doubt_ = doubt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse) {
          return mergeFrom((pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse other) {
        if (other == pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse.getDefaultInstance()) return this;
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (other.getTargetId() != 0L) {
          setTargetId(other.getTargetId());
        }
        if (other.hasChatData()) {
          mergeChatData(other.getChatData());
        }
        if (other.getDoubt() != false) {
          setDoubt(other.getDoubt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int channel_ ;
      /**
       * <pre>
       *频道
       * </pre>
       *
       * <code>int32 channel = 1;</code>
       * @return The channel.
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <pre>
       *频道
       * </pre>
       *
       * <code>int32 channel = 1;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(int value) {
        
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *频道
       * </pre>
       *
       * <code>int32 channel = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = 0;
        onChanged();
        return this;
      }

      private long targetId_ ;
      /**
       * <pre>
       *目标ID，好友聊天时传玩家ID
       * </pre>
       *
       * <code>int64 target_id = 2;</code>
       * @return The targetId.
       */
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <pre>
       *目标ID，好友聊天时传玩家ID
       * </pre>
       *
       * <code>int64 target_id = 2;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(long value) {
        
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标ID，好友聊天时传玩家ID
       * </pre>
       *
       * <code>int64 target_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        
        targetId_ = 0L;
        onChanged();
        return this;
      }

      private pb.xiugou.x1.protobuf.chat.Chat.PbChatData chatData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.xiugou.x1.protobuf.chat.Chat.PbChatData, pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder, pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder> chatDataBuilder_;
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       * @return Whether the chatData field is set.
       */
      public boolean hasChatData() {
        return chatDataBuilder_ != null || chatData_ != null;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       * @return The chatData.
       */
      public pb.xiugou.x1.protobuf.chat.Chat.PbChatData getChatData() {
        if (chatDataBuilder_ == null) {
          return chatData_ == null ? pb.xiugou.x1.protobuf.chat.Chat.PbChatData.getDefaultInstance() : chatData_;
        } else {
          return chatDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder setChatData(pb.xiugou.x1.protobuf.chat.Chat.PbChatData value) {
        if (chatDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatData_ = value;
          onChanged();
        } else {
          chatDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder setChatData(
          pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder builderForValue) {
        if (chatDataBuilder_ == null) {
          chatData_ = builderForValue.build();
          onChanged();
        } else {
          chatDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder mergeChatData(pb.xiugou.x1.protobuf.chat.Chat.PbChatData value) {
        if (chatDataBuilder_ == null) {
          if (chatData_ != null) {
            chatData_ =
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData.newBuilder(chatData_).mergeFrom(value).buildPartial();
          } else {
            chatData_ = value;
          }
          onChanged();
        } else {
          chatDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public Builder clearChatData() {
        if (chatDataBuilder_ == null) {
          chatData_ = null;
          onChanged();
        } else {
          chatData_ = null;
          chatDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder getChatDataBuilder() {
        
        onChanged();
        return getChatDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      public pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder getChatDataOrBuilder() {
        if (chatDataBuilder_ != null) {
          return chatDataBuilder_.getMessageOrBuilder();
        } else {
          return chatData_ == null ?
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData.getDefaultInstance() : chatData_;
        }
      }
      /**
       * <pre>
       *聊天信息
       * </pre>
       *
       * <code>.pb.PbChatData chat_data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.xiugou.x1.protobuf.chat.Chat.PbChatData, pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder, pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder> 
          getChatDataFieldBuilder() {
        if (chatDataBuilder_ == null) {
          chatDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.xiugou.x1.protobuf.chat.Chat.PbChatData, pb.xiugou.x1.protobuf.chat.Chat.PbChatData.Builder, pb.xiugou.x1.protobuf.chat.Chat.PbChatDataOrBuilder>(
                  getChatData(),
                  getParentForChildren(),
                  isClean());
          chatData_ = null;
        }
        return chatDataBuilder_;
      }

      private boolean doubt_ ;
      /**
       * <pre>
       *是否可疑
       * </pre>
       *
       * <code>bool doubt = 4;</code>
       * @return The doubt.
       */
      public boolean getDoubt() {
        return doubt_;
      }
      /**
       * <pre>
       *是否可疑
       * </pre>
       *
       * <code>bool doubt = 4;</code>
       * @param value The doubt to set.
       * @return This builder for chaining.
       */
      public Builder setDoubt(boolean value) {
        
        doubt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否可疑
       * </pre>
       *
       * <code>bool doubt = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubt() {
        
        doubt_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ChatToRpcResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.ChatToRpcResponse)
    private static final pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse();
    }

    public static pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatToRpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChatToRpcResponse>() {
      @java.lang.Override
      public ChatToRpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatToRpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatToRpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatToRpcResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.xiugou.x1.protobuf.chat.ChatRpc.ChatToRpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ChatToRpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ChatToRpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ChatToRpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ChatToRpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rChatRpc.proto\022\002pb\032\nChat.proto\"\236\001\n\020Chat" +
      "ToRpcRequest\022\017\n\007channel\030\001 \001(\005\022\021\n\ttarget_" +
      "id\030\002 \001(\003\022!\n\tchat_data\030\003 \001(\0132\016.pb.PbChatD" +
      "ata\022\r\n\005doubt\030\004 \001(\010\022\023\n\013ori_content\030\005 \001(\t\"" +
      "\037\n\005Proto\022\013\n\007UNKNOWN\020\000\022\t\n\002ID\020\221\253\334\001\"\212\001\n\021Cha" +
      "tToRpcResponse\022\017\n\007channel\030\001 \001(\005\022\021\n\ttarge" +
      "t_id\030\002 \001(\003\022!\n\tchat_data\030\003 \001(\0132\016.pb.PbCha" +
      "tData\022\r\n\005doubt\030\004 \001(\010\"\037\n\005Proto\022\013\n\007UNKNOWN" +
      "\020\000\022\t\n\002ID\020\221\253\334\001B4\n\032pb.xiugou.x1.protobuf.c" +
      "hat\252\002\025pb.xiugou.x1.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.xiugou.x1.protobuf.chat.Chat.getDescriptor(),
        });
    internal_static_pb_ChatToRpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_ChatToRpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ChatToRpcRequest_descriptor,
        new java.lang.String[] { "Channel", "TargetId", "ChatData", "Doubt", "OriContent", });
    internal_static_pb_ChatToRpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_ChatToRpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ChatToRpcResponse_descriptor,
        new java.lang.String[] { "Channel", "TargetId", "ChatData", "Doubt", });
    pb.xiugou.x1.protobuf.chat.Chat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
